namespace Axom.Compiler.Lexing;

public enum TokenKind
{
    BadToken,
    EndOfFile,
    NewLine,
    Identifier,
    PrintKeyword,
    PrintlnKeyword,
    InputKeyword,
    LetKeyword,
    MutKeyword,
    FnKeyword,
    ReturnKeyword,
    TypeKeyword,
    MatchKeyword,
    TrueKeyword,
    FalseKeyword,
    NumberLiteral,
    StringLiteral,
    EqualsToken,
    Arrow,
    ArrowType,
    Plus,
    Minus,
    Star,
    Slash,
    Comma,
    Colon,
    Dot,
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    Semicolon
}
