namespace Axom.Cli;

internal static class ProjectScaffolder
{
    public static bool TryScaffoldApiProject(string projectPath, bool force, out string? error)
    {
        error = null;
        if (string.IsNullOrWhiteSpace(projectPath))
        {
            error = "Project path cannot be empty.";
            return false;
        }

        if (Directory.Exists(projectPath))
        {
            var hasContents = Directory.EnumerateFileSystemEntries(projectPath).Any();
            if (hasContents && !force)
            {
                error = "Target directory already exists and is not empty. Use --force to overwrite scaffold files.";
                return false;
            }
        }

        Directory.CreateDirectory(projectPath);
        var routesPath = Path.Combine(projectPath, "routes");
        var scriptsPath = Path.Combine(projectPath, "scripts");
        Directory.CreateDirectory(routesPath);
        Directory.CreateDirectory(scriptsPath);

        var projectName = new DirectoryInfo(projectPath).Name;

        WriteFile(Path.Combine(projectPath, "main.axom"), MainSource);
        WriteFile(Path.Combine(routesPath, "health_get.axom"), HealthRoute);
        WriteFile(Path.Combine(routesPath, "users__id_int_get.axom"), UsersRoute);
        WriteFile(Path.Combine(routesPath, "search_get.axom"), SearchRoute);
        WriteFile(Path.Combine(routesPath, "request_info_get.axom"), RequestInfoRoute);
        WriteFile(Path.Combine(routesPath, "missing_get.axom"), MissingRoute);
        WriteFile(Path.Combine(projectPath, ".gitignore"), GitIgnore);
        WriteFile(Path.Combine(projectPath, "Dockerfile"), Dockerfile);
        WriteFile(Path.Combine(projectPath, "docker-compose.yml"), DockerCompose);
        WriteFile(Path.Combine(projectPath, "Makefile"), Makefile);
        WriteFile(Path.Combine(projectPath, "api.http"), ApiHttp);
        WriteFile(Path.Combine(scriptsPath, "document-endpoints.ps1"), DocumentEndpointsPowerShell);
        WriteFile(Path.Combine(projectPath, "ENDPOINTS.md"), EndpointsDoc);
        WriteFile(Path.Combine(projectPath, "README.md"), BuildReadme(projectName));
        return true;
    }

    private static void WriteFile(string path, string content)
    {
        File.WriteAllText(path, content);
    }

    private static string BuildReadme(string projectName)
    {
        return $"""
# {projectName}

Generated by `axom init`.

## Quick Start

```bash
axom serve main.axom --host 127.0.0.1 --port 8080
```

In another terminal:

```bash
curl -i http://127.0.0.1:8080/health
curl -i http://127.0.0.1:8080/users/42
curl -i \"http://127.0.0.1:8080/search?q=axom&page=2\"
curl -i http://127.0.0.1:8080/request/info
curl -i http://127.0.0.1:8080/missing
```

## Run Without Web

You can use this project as a normal script project and ignore `routes/`.

```bash
axom check main.axom
axom run main.axom
```

`routes/` is only used by `axom serve`.

## Docker

Build and run:

```bash
docker compose up --build
```

Then call endpoints at `http://127.0.0.1:8080`.

## Endpoint Documentation

Quick manual smoke test file:

- `api.http` (works in VS Code REST Client / JetBrains HTTP Client)

Regenerate endpoint docs (macOS/Linux):

```bash
make endpoints-docs
```

Regenerate endpoint docs (Windows PowerShell):

```powershell
powershell -ExecutionPolicy Bypass -File .\scripts\document-endpoints.ps1
```

Both commands update `ENDPOINTS.md`.

## What This Scaffold Shows

- route params: `route_param_int("id")`
- query params: `query_param("q")`, `query_param_int("page")`
- request context: `request_method()`, `request_path()`
- explicit response override: `respond(status, body)`
""";
    }

    private const string MainSource = """
print "axom api bootstrap"
""";

    private const string HealthRoute = """
print "health route"
""";

    private const string UsersRoute = """
print match route_param_int("id") {
  Ok(id) -> id
  Error(_) -> -1
}
print "user route"
""";

    private const string SearchRoute = """
print match query_param("q") {
  Ok(v) -> v
  Error(_) -> "missing"
}
print match query_param_int("page") {
  Ok(v) -> v
  Error(_) -> -1
}
""";

    private const string RequestInfoRoute = """
print request_method()
print request_path()
""";

    private const string MissingRoute = """
respond(404, "missing route example")
""";

    private const string GitIgnore = """
out/
.run/
bin/
obj/
""";

    private const string Makefile = """
.PHONY: serve check run endpoints-docs

serve:
	axom serve main.axom --host 127.0.0.1 --port 8080

check:
	axom check main.axom

run:
	axom run main.axom

endpoints-docs:
	cat > ENDPOINTS.md <<'EOF'
	# Endpoints

	## GET /health
	- Source: `routes/health_get.axom`
	- Behavior: returns health route text.

	## GET /users/:id<int>
	- Source: `routes/users__id_int_get.axom`
	- Behavior: demonstrates route params via `route_param_int("id")`.

	## GET /search
	- Source: `routes/search_get.axom`
	- Query: `q` (String), `page` (Int)
	- Behavior: demonstrates query params via `query_param*`.

	## GET /request/info
	- Source: `routes/request_info_get.axom`
	- Behavior: prints request method/path.

	## GET /missing
	- Source: `routes/missing_get.axom`
	- Behavior: explicit `404` via `respond(404, ...)`.
	EOF
	@echo "Wrote ENDPOINTS.md"
""";

    private const string EndpointsDoc = """
# Endpoints

## GET /health
- Source: `routes/health_get.axom`
- Behavior: returns health route text.

## GET /users/:id<int>
- Source: `routes/users__id_int_get.axom`
- Behavior: demonstrates route params via `route_param_int("id")`.

## GET /search
- Source: `routes/search_get.axom`
- Query: `q` (String), `page` (Int)
- Behavior: demonstrates query params via `query_param*`.

## GET /request/info
- Source: `routes/request_info_get.axom`
- Behavior: prints request method/path.

## GET /missing
- Source: `routes/missing_get.axom`
- Behavior: explicit `404` via `respond(404, ...)`.
""";

    private const string ApiHttp = """
### health
GET http://127.0.0.1:8080/health

### user by id
GET http://127.0.0.1:8080/users/42

### query params
GET http://127.0.0.1:8080/search?q=axom&page=2

### request context
GET http://127.0.0.1:8080/request/info

### explicit 404
GET http://127.0.0.1:8080/missing
""";

    private const string DocumentEndpointsPowerShell = """
$content = @'
# Endpoints

## GET /health
- Source: `routes/health_get.axom`
- Behavior: returns health route text.

## GET /users/:id<int>
- Source: `routes/users__id_int_get.axom`
- Behavior: demonstrates route params via `route_param_int("id")`.

## GET /search
- Source: `routes/search_get.axom`
- Query: `q` (String), `page` (Int)
- Behavior: demonstrates query params via `query_param*`.

## GET /request/info
- Source: `routes/request_info_get.axom`
- Behavior: prints request method/path.

## GET /missing
- Source: `routes/missing_get.axom`
- Behavior: explicit `404` via `respond(404, ...)`.
'@

Set-Content -Path "ENDPOINTS.md" -Value $content -NoNewline
Write-Host "Wrote ENDPOINTS.md"
""";

    private const string Dockerfile = """
FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install -g axom.cli --version 0.4.0-alpha.5
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /app
COPY . .

EXPOSE 8080

CMD ["axom", "serve", "main.axom", "--host", "0.0.0.0", "--port", "8080"]
""";

    private const string DockerCompose = """
services:
  axom:
    build: .
    ports:
      - "8080:8080"
""";
}
