namespace Axom.Cli;

internal static class ProjectScaffolder
{
    public static bool TryScaffoldApiProject(string projectPath, bool force, out string? error)
    {
        error = null;
        if (string.IsNullOrWhiteSpace(projectPath))
        {
            error = "Project path cannot be empty.";
            return false;
        }

        if (Directory.Exists(projectPath))
        {
            var hasContents = Directory.EnumerateFileSystemEntries(projectPath).Any();
            if (hasContents && !force)
            {
                error = "Target directory already exists and is not empty. Use --force to overwrite scaffold files.";
                return false;
            }
        }

        Directory.CreateDirectory(projectPath);
        var routesPath = Path.Combine(projectPath, "routes");
        Directory.CreateDirectory(routesPath);

        var projectName = new DirectoryInfo(projectPath).Name;

        WriteFile(Path.Combine(projectPath, "main.axom"), MainSource);
        WriteFile(Path.Combine(routesPath, "health_get.axom"), HealthRoute);
        WriteFile(Path.Combine(routesPath, "users__id_int_get.axom"), UsersRoute);
        WriteFile(Path.Combine(routesPath, "search_get.axom"), SearchRoute);
        WriteFile(Path.Combine(routesPath, "request_info_get.axom"), RequestInfoRoute);
        WriteFile(Path.Combine(routesPath, "missing_get.axom"), MissingRoute);
        WriteFile(Path.Combine(projectPath, ".gitignore"), GitIgnore);
        WriteFile(Path.Combine(projectPath, "Dockerfile"), Dockerfile);
        WriteFile(Path.Combine(projectPath, "docker-compose.yml"), DockerCompose);
        WriteFile(Path.Combine(projectPath, "README.md"), BuildReadme(projectName));
        return true;
    }

    private static void WriteFile(string path, string content)
    {
        File.WriteAllText(path, content);
    }

    private static string BuildReadme(string projectName)
    {
        return $"""
# {projectName}

Generated by `axom init`.

## Quick Start

```bash
axom serve main.axom --host 127.0.0.1 --port 8080
```

In another terminal:

```bash
curl -i http://127.0.0.1:8080/health
curl -i http://127.0.0.1:8080/users/42
curl -i \"http://127.0.0.1:8080/search?q=axom&page=2\"
curl -i http://127.0.0.1:8080/request/info
curl -i http://127.0.0.1:8080/missing
```

## Run Without Web

You can use this project as a normal script project and ignore `routes/`.

```bash
axom check main.axom
axom run main.axom
```

`routes/` is only used by `axom serve`.

## Docker

Build and run:

```bash
docker compose up --build
```

Then call endpoints at `http://127.0.0.1:8080`.

## What This Scaffold Shows

- route params: `route_param_int("id")`
- query params: `query_param("q")`, `query_param_int("page")`
- request context: `request_method()`, `request_path()`
- explicit response override: `respond(status, body)`
""";
    }

    private const string MainSource = """
print "axom api bootstrap"
""";

    private const string HealthRoute = """
print "health route"
""";

    private const string UsersRoute = """
print match route_param_int("id") {
  Ok(id) -> id
  Error(_) -> -1
}
print "user route"
""";

    private const string SearchRoute = """
print match query_param("q") {
  Ok(v) -> v
  Error(_) -> "missing"
}
print match query_param_int("page") {
  Ok(v) -> v
  Error(_) -> -1
}
""";

    private const string RequestInfoRoute = """
print request_method()
print request_path()
""";

    private const string MissingRoute = """
respond(404, "missing route example")
""";

    private const string GitIgnore = """
out/
.run/
bin/
obj/
""";

    private const string Dockerfile = """
FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install -g axom --version 0.4.0-alpha.4
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /app
COPY . .

EXPOSE 8080

CMD ["axom", "serve", "main.axom", "--host", "0.0.0.0", "--port", "8080"]
""";

    private const string DockerCompose = """
services:
  axom:
    build: .
    ports:
      - "8080:8080"
""";
}
